export const CATEGORY = {
  PROGRAM: {
    VALUE: 1,
    LABEL: 'Lập trình',
    SUB_CATEGORY: {
      WEBSITE: { VALUE: 2, LABEL: 'Website' },
      MOBILE: { VALUE: 5, LABEL: 'Mobile' },
      DESKTOP: { VALUE: 6, LABEL: 'Desktop' },
    }
  },
  DESIGN: {
    VALUE: 3,
    LABEL: 'Thiết kế',
    SUB_CATEGORY: {
      GAME: { VALUE: 7, LABEL: 'Game' },
      LOGO: { VALUE: 8, LABEL: 'Logo' },
      BANNER: { VALUE: 9, LABEL: 'Banner' },
    }
  },
  LANGUAGE: {
    VALUE: 4,
    LABEL: 'Ngoại ngữ',
    SUB_CATEGORY: {
      LAOS: { VALUE: 10, LABEL: 'Lào' },
      ESPAGNOL: { VALUE: 11, LABEL: 'Tây Ban Nha' },
      RUSSIA: { VALUE: 12, LABEL: 'Nga' },
      ENGLISH: { VALUE: 13, LABEL: 'Anh' },
    }
  }
}

export const CATEGORY_MAP = new Map([
  [CATEGORY.PROGRAM.VALUE, CATEGORY.PROGRAM.LABEL],
  [CATEGORY.PROGRAM.SUB_CATEGORY.WEBSITE.VALUE, CATEGORY.PROGRAM.SUB_CATEGORY.WEBSITE.LABEL],
  [CATEGORY.PROGRAM.SUB_CATEGORY.MOBILE.VALUE, CATEGORY.PROGRAM.SUB_CATEGORY.MOBILE.LABEL],
  [CATEGORY.PROGRAM.SUB_CATEGORY.DESKTOP.VALUE, CATEGORY.PROGRAM.SUB_CATEGORY.DESKTOP.LABEL],
  [CATEGORY.DESIGN.VALUE, CATEGORY.DESIGN.LABEL],
  [CATEGORY.DESIGN.SUB_CATEGORY.GAME.VALUE, CATEGORY.DESIGN.SUB_CATEGORY.GAME.LABEL],
  [CATEGORY.DESIGN.SUB_CATEGORY.LOGO.VALUE, CATEGORY.DESIGN.SUB_CATEGORY.LOGO.LABEL],
  [CATEGORY.DESIGN.SUB_CATEGORY.BANNER.VALUE, CATEGORY.DESIGN.SUB_CATEGORY.BANNER.LABEL],
  [CATEGORY.LANGUAGE.VALUE, CATEGORY.LANGUAGE.LABEL],
  [CATEGORY.LANGUAGE.SUB_CATEGORY.LAOS.VALUE, CATEGORY.LANGUAGE.SUB_CATEGORY.LAOS.LABEL],
  [CATEGORY.LANGUAGE.SUB_CATEGORY.ESPAGNOL.VALUE, CATEGORY.LANGUAGE.SUB_CATEGORY.ESPAGNOL.LABEL],
  [CATEGORY.LANGUAGE.SUB_CATEGORY.RUSSIA.VALUE, CATEGORY.LANGUAGE.SUB_CATEGORY.RUSSIA.LABEL],
  [CATEGORY.LANGUAGE.SUB_CATEGORY.ENGLISH.VALUE, CATEGORY.LANGUAGE.SUB_CATEGORY.ENGLISH.LABEL],
])

export const NAV_ITEMS = [
  { NAME: 'Trang chủ', PATH: '/' },
  { NAME: 'Lập trình', PATH: `/category/${CATEGORY.PROGRAM.VALUE}/sub-category/0/page/1` },
  { NAME: 'Thiết kế', PATH: `/category/${CATEGORY.DESIGN.VALUE}/sub-category/0/page/1` },
  { NAME: 'Ngoại ngữ', PATH: `/category/${CATEGORY.LANGUAGE.VALUE}/sub-category/0/page/1` },
  { NAME: 'Giới thiệu', PATH: '/about' }
]

export const CATEGORY_LEVEL = {
  LEVEL_1: 1,
  LEVEL_2: 2
}
